[package]
name = "huma-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
huma-bytecode = { path = "../crates/huma-bytecode" }
huma-hmi = { path = "../crates/huma-hmi" }
huma-syntax = { path = "../crates/huma-syntax" }
serde_json = "1.0"

[[bin]]
name = "lexer_parser"
path = "fuzz_targets/lexer_parser.rs"
test = false
doc = false
bench = false

[[bin]]
name = "hmi_frame"
path = "fuzz_targets/hmi_frame.rs"
test = false
doc = false
bench = false

[[bin]]
name = "bytecode_verifier"
path = "fuzz_targets/bytecode_verifier.rs"
test = false
doc = false
bench = false

[workspace]
