[package]
name = "huma-lsp"
version = "0.6.0"
edition = "2021"
rust-version = "1.94.1"
license = "MIT"
description = "Language Server Protocol (LSP) server for the Hüma programming language."

[[bin]]
name = "huma-lsp"
path = "src/main.rs"

[dependencies]
huma-syntax = { path = "../huma-syntax" }
huma-stdlib = { path = "../huma-stdlib" }
anyhow = "1"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "io-std"] }
tower-lsp = "0.20"
walkdir = "2"
regex = "1"
